### ISSUE TITLE
queryParams bug with undefined value

### ISSUE THREAD

**Issue by NamesMT** [rainxh11/vue-useurl#3]
```
console.log(
  (useUrl({
    queryParams: {
      someKey: undefined,
    },
  }, `https://example.com`)).url.value
)
```
This will result in `https://example.com/?someKey=undefined`
Which is a param with the string value 'undefined' and is truthy, which causes unwanted behavior in many ways.

Could be fixed with a small modification to filter at [line 87](https://github.com/rainxh11/vue-useurl/blob/master/src/index.ts#L87)

I don't currently have time to make a PR sorry.
Thanks a lot.

**Comment by rainxh11** [comment]
Thanks, i fixed it

**Comment by NamesMT** [comment]
Hi, thanks for the quick patch, but it seems like you haven't publish it to npmjs yet.

**Comment by rainxh11** [comment]
> Hi, thanks for the quick patch, but it seems like you haven't publish it to npmjs yet.

i published the fixed version

**Comment by NamesMT** [comment]
Hi, after testing the bug actually still exists, a bit more modification at [line 81 or 78](https://github.com/rainxh11/vue-useurl/blob/master/src/index.ts#L81) should then fix it, thanks!

**Comment by NamesMT** [comment]
Btw FYI the filter at line 87 doesn't seem to have any effect, as we always get truthy value of "${key}=" returned even when the value is empty string/null (and passing null also results in the param having the "null" string)

**Comment by NamesMT** [comment]
Hi, tagging for notification @rainxh11 .
